Layout/LineLength:
  Max: 120
  AllowedPatterns: ['\A#']

Naming/InclusiveLanguage:
  Enabled: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/Documentation:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Style/SymbolArray:
  EnforcedStyle: brackets

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

AllCops:
  NewCops: enable
